packages:
  - "packages/*"
  - "services/*"
allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  unrs-resolver: true
  workerd: true
